# Your configuration properties
#quarkus.rest-client."org.acme.rest.client.QuarkusExtensionsService".url=https://stage.code.quarkus.io/api 
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
#quarkus.rest-client.extensions-api.tls-configuration-name=tls-disabled

quarkus.rest-client.gitlab-api.url=${GITLAB_API}
quarkus.rest-client.gitlab-api.scope=jakarta.inject.Singleton
quarkus.rest-client.gitlab-api.disable-default-mapper=true

#quarkus.rest-client.logging.scope=request-response
#quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

gitlab.token=${GitlabToken}
gitlab.projectid=${GITLAB_PROJECT_ID}
gitlab.timeout=10
gitlab.targetdir=${GITLAB_TARGET_DIR}

graph.tenant-id=${AzureAppTenantName}
graph.client-id=${AzureAppClientId}
graph.certificate-base64=${AzureCertPFX}
graph.certificate-password=${AzureAppCertPFXPassword}

sharepoint.host-name=${SHAREPOINT_HOST_NAME}
sharepoint.site-name=${SHAREPOINT_SITE_NAME}
sharepoint.target-dir=${SHAREPOINT_FOLDER_PATH}

